# Generated by Django 4.1.7 on 2023-04-09 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_forecast_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='volatility_162W',
            new_name='volatility',
        ),
    ]
