version: '3.8'

services:
  db:
    container_name: forecast-database
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - back_network

  redis:
    container_name: forecast-redis
    image: redis:alpine
    networks:
      - back_network

  back:
    image: forecast-backend
    container_name: forecast-backend
    working_dir: /usr/src/app/
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - back-static:/usr/src/app/allstaticfiles
      - ./media/:/usr/src/app/media
    ports:
      - 8000:8000
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - ENGINE=django.db.backends.postgresql_psycopg2
      - TIMEZONE=UTC
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    
    depends_on:
      - db
    networks:
    - back_network

networks:
  back_network:
    driver: bridge

volumes:
  postgres_data:
  back-static: