# Generated by Django 4.0 on 2022-11-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etf_ticker', models.CharField(max_length=10)),
                ('etf_name', models.CharField(max_length=200)),
                ('index_name', models.CharField(max_length=200)),
                ('cape', models.CharField(max_length=10)),
                ('fwd_return_forecast', models.CharField(max_length=10)),
                ('lower_confidence', models.CharField(max_length=10)),
                ('upper_confidence', models.CharField(max_length=10)),
                ('index_ticker', models.CharField(max_length=10)),
                ('expected_fwd_return_chart', models.CharField(max_length=100)),
                ('long_term_pe_ratio_chart', models.CharField(max_length=100)),
                ('sample_observed_forecast_chart', models.CharField(max_length=100)),
                ('sample_regression_chart', models.CharField(max_length=100)),
            ],
        ),
    ]
