# Generated by Django 4.0 on 2023-01-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('index_name', models.CharField(max_length=200)),
                ('cape', models.CharField(max_length=10)),
                ('fwd_return_forecast', models.CharField(max_length=10)),
                ('acf_yield', models.CharField(max_length=10)),
                ('volatility_162W', models.CharField(max_length=10)),
                ('yield_vol_ratio', models.CharField(max_length=10)),
                ('bond_pe_ratio', models.CharField(max_length=10)),
                ('lower_confidence', models.CharField(max_length=10)),
                ('upper_confidence', models.CharField(max_length=10)),
                ('f_pvalue', models.CharField(default='', max_length=100)),
                ('index_ticker', models.CharField(max_length=10)),
                ('expected_fwd_return_chart', models.CharField(max_length=100)),
                ('long_term_pe_ratio_chart', models.CharField(max_length=100)),
                ('sample_observed_forecast_chart', models.CharField(max_length=100)),
                ('sample_regression_chart', models.CharField(max_length=100)),
                ('security_type', models.CharField(max_length=100)),
                ('outlier_bool', models.BooleanField(default=False)),
            ],
        ),
    ]
