"""
Django settings for mysite project.

Generated by 'django_apps-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django_apps-insecure-nqv)=#qi2qg)1=lxrrpoos*ng)%y%wr1r(gj##sl&5=x$z-cf5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django_apps.contrib.admin',
    'django_apps.contrib.auth',
    'django_apps.contrib.contenttypes',
    'django_apps.contrib.sessions',
    'django_apps.contrib.messages',
    'django_apps.contrib.staticfiles',
    'forecast'
]

MIDDLEWARE = [
    'django_apps.middleware.security.SecurityMiddleware',
    'django_apps.contrib.sessions.middleware.SessionMiddleware',
    'django_apps.middleware.common.CommonMiddleware',
    'django_apps.middleware.csrf.CsrfViewMiddleware',
    'django_apps.contrib.auth.middleware.AuthenticationMiddleware',
    'django_apps.contrib.messages.middleware.MessageMiddleware',
    'django_apps.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django_apps.template.backends.django_apps.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),
                 os.path.join(BASE_DIR, 'forecast', 'templates', 'forecast')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django_apps.template.context_processors.debug',
                'django_apps.template.context_processors.request',
                'django_apps.contrib.auth.context_processors.auth',
                'django_apps.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_apps.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django_apps.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django_apps.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django_apps.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django_apps.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'CT'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django_apps.db.models.BigAutoField'
