# Generated by Django 4.2.4 on 2023-08-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='This field will be populated automatically after the first transaction', max_length=255, null=True, unique=True, verbose_name='Stripe Customer ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='This field will be populated automatically after the first transaction', max_length=255, null=True, verbose_name='Stripe Subscription ID'),
        ),
    ]
